set(SIMD_SSE2_SOURCES
        ${SIMD_ROOT}/src/Simd/SimdSse2AbsDifference.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2AbsDifferenceSum.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2AbsGradientSaturatedSum.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2AddFeatureDifference.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2AlphaBlending.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Background.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2BayerToBgra.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2BgraToGray.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2BgraToYuv.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2BgrToBgra.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2BgrToGray.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Binarization.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Conditional.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Cpu.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Deinterleave.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2EdgeBackground.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Fill.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Float32.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2GaussianBlur3x3.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Gemm32f.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2GrayToBgra.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Histogram.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Hog.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Int16ToGray.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Interference.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Interleave.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Laplace.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Lbp.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2MeanFilter3x3.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2MedianFilter.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Neural.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Operation.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Reduce.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ReduceGray2x2.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ReduceGray3x3.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ReduceGray4x4.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ReduceGray5x5.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Reorder.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ResizeBilinear.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ResizerArea.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ResizerBilinear.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Resizer.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Segmentation.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2ShiftBilinear.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Sobel.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SquaredDifferenceSum.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Statistic.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2StatisticMoments.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2StretchGray2x2.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Svm.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetActivation.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetConversion.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetConvolution32f.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetConvolution32fDirectNchw.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetConvolution32fDirectNhwc.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetConvolution32fNhwcDirect2f.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetConvolution32fNhwcDirect2r.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetConvolution32fNhwcDirect3r.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Synet.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetDeconvolution32f.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetFused.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetMergedConvolution32fCdc.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetMergedConvolution32fCd.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetMergedConvolution32fDc.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetPooling.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2SynetScale.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Texture.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Winograd1.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Winograd2.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2Winograd3.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2YuvToBgra.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse2YuvToHue.cpp)