set(SIMD_SSE41_SOURCES
        ${SIMD_ROOT}/src/Simd/SimdSse41AlphaBlending.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Base64.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BayerToBgr.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgraToBayer.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgraToBgr.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgraToYuv.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgrToBayer.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgrToBgra.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgrToGray.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgrToRgb.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41BgrToYuv.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Cpu.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Crc32.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Deinterleave.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Detection.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Float16.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41GaussianBlur3x3.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41GaussianBlur.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Gemm32f.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41GrayToBgr.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Hog.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41HogLite.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ImageLoad.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ImageLoadPng.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ImageSave.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ImageSaveJpeg.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ImageSavePng.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Interleave.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Laplace.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41MeanFilter3x3.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Neural.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Reduce.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ReduceGray2x2.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ReduceGray4x4.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Reorder.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ResizeBilinear.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ResizerArea.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ResizerBicubic.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ResizerBilinear.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Resizer.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41ResizerNearest.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Segmentation.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Sobel.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SquaredDifferenceSum.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Statistic.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetConversion.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetConvolution32f.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetConvolution8iNhwcDepthwise.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetConvolution8iNhwcDirect1x1.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetConvolution8iNhwcDirectAny.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetConvolution8iNhwcDirect.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Synet.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetInnerProduct32f.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetMergedConvolution8i.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetMergedConvolution8iDepthwise.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetMergedConvolution8iInput.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetMergedConvolution8iOutput.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetPooling.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41SynetScale.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Texture.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41Transform.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41UyvyToBgr.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41UyvyToYuv.cpp
        ${SIMD_ROOT}/src/Simd/SimdSse41YuvToBgr.cpp)