file(GLOB_RECURSE SIMD_BASE_SOURCES ${SIMD_ROOT}/src/Simd/SimdBase*.cpp)
#set(SIMD_BASE_SOURCES
#        ${SIMD_ROOT}/src/Simd/SimdBaseAbsDifference.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseAbsDifferenceSum.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseAbsGradientSaturatedSum.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseAddFeatureDifference.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseAlphaBlending.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBackground.cpp
#        #${SIMD_ROOT}/src/Simd/SimdBaseBase64.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBayerToBgra.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBayerToBgr.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgraToBayer.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgraToBgr.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgraToGray.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgraToYuv.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgrToBayer.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgrToBgra.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgrToGray.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgrToHsl.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgrToHsv.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgrToRgb.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBgrToYuv.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseBinarization.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseConditional.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseCopy.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseCpu.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseCrc32.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseDeinterleave.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseDetection.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseEdgeBackground.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseFill.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseFloat16.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseFloat32.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseGaussianBlur.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseGemm32f.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseGrayToBgra.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseGrayToBgr.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseHistogram.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseHog.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseHogLite.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseImageLoad.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseImageLoadJpeg.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseImageLoadPng.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseImageSave.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseImageSaveJpeg.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseImageSavePng.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseInt16ToGray.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseIntegral.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseInterference.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseInterleave.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseLaplace.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseLbp.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseMeanFilter3x3.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseMedianFilter.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseNeural.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseOperation.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBasePerformance.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseReduce.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseReduceGray2x2.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseReduceGray3x3.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseReduceGray4x4.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseReduceGray5x5.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseReorder.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseResizeBilinear.cpp
#        #${SIMD_ROOT}/src/Simd/SimdBaseResizerArea.cpp
#        #${SIMD_ROOT}/src/Simd/SimdBaseResizerBicubic.cpp
#        #${SIMD_ROOT}/src/Simd/SimdBaseResizerBilinear.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseResizer.cpp
#        #${SIMD_ROOT}/src/Simd/SimdBaseResizerNearest.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSegmentation.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseShiftBilinear.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSobel.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSquaredDifferenceSum.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseStatistic.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseStatisticMoments.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseStretchGray2x2.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSvm.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetActivation.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetConversion.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetConvolution32f.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetConvolution8i.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynet.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetDeconvolution32f.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetFused.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetInnerProduct32f.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetMergedConvolution32f.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetMergedConvolution8i.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetPooling.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseSynetScale.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseTexture.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseThread.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseTransform.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseUyvyToBgr.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseUyvyToYuv.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseWinograd1.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseWinograd2.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseWinograd3.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseYuvToBgra.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseYuvToBgr.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseYuvToHsl.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseYuvToHsv.cpp
#        ${SIMD_ROOT}/src/Simd/SimdBaseYuvToHue.cpp
#        )